services:
  app:
    build: .
    volumes:
      - .:/workspace:cached
    ports:
      - "8888:8888"
      - "8501:8501"
    depends_on:
      - opensearch
    environment:
      - OPENSEARCH_URL=https://opensearch:9200
      - OPENSEARCH_USER=admin
      - OPENSEARCH_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD:-SecureOpenSearch@2024!}

  opensearch:
    image: opensearchproject/opensearch:2.15.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD:-SecureOpenSearch@2024!}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.15.0
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=["https://opensearch:9200"]
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD:-SecureOpenSearch@2024!}
      - OPENSEARCH_SSL_VERIFICATIONMODE=none
    depends_on:
      - opensearch
