OPENSEARCH_HOST = "http://localhost:9200"
INDEX_NAME = "vector_lab_docs"
MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
EMBEDDING_DIM = 384

DEFAULT_HNSW_M = 16
DEFAULT_EF_CONSTRUCTION = 128
DEFAULT_EF_SEARCH = 100
