services:
  opensearch:
    image: opensearchproject/opensearch:2.13.0
    container_name: os-faiss-demo
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  app:
    build: ./app
    container_name: os-faiss-app
    environment:
      - OPENSEARCH_URL=http://opensearch:9200
      - INDEX_NAME=multimodal-faiss-demo
      - EMBEDDING_MODEL=clip-ViT-B-32
    depends_on:
      opensearch:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./samples:/app/samples
